"""Silver layer: cleansing, typing, deduplication, and validation."""
import json
import logging
import re
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation

from dateutil.parser import parse as parse_date, ParserError

from src.config import BRONZE_SCHEMA, BRONZE_TABLE, SILVER_SCHEMA, SILVER_TABLE
from src.db import get_cursor, truncate_table

logger = logging.getLogger(__name__)

# ── Category normalization mapping ──────────────────────────────────
# Generated by the Semantic Classification Agent (see agents/semantic_classify.py).
# Full 98 → ~8 mapping. Edit this dict to override agent suggestions.
CATEGORY_MAPPING = {
    # Elevator / Vertical Transport
    "elevator": "Elevator",
    "elevator/escalator": "Elevator",
    "lift": "Elevator",
    "vertical transport": "Elevator",
    # Electrical / Power
    "electrical": "Electrical",
    "electrical systems": "Electrical",
    "elec": "Electrical",
    "power": "Electrical",
    "power issue": "Electrical",
    "lighting": "Electrical",
    "generator": "Electrical",
    "ups/battery": "Electrical",
    # HVAC / Climate
    "hvac": "HVAC",
    "a/c": "HVAC",
    "climate control": "HVAC",
    "heating/cooling": "HVAC",
    "temperature control": "HVAC",
    "humidity": "HVAC",
    "indoor air quality": "HVAC",
    # HVAC — variants from actual CSV
    "ac": "HVAC",
    "air conditioning": "HVAC",
    "heating cooling": "HVAC",
    "hvac system": "HVAC",
    "cold": "HVAC",
    # Plumbing / Water
    "plumbing": "Plumbing",
    "plumbing issue": "Plumbing",
    "water/plumbing": "Plumbing",
    "water issue": "Plumbing",
    "flooding": "Plumbing",
    "leak": "Plumbing",
    # Fire / Safety
    "fire safety": "Fire & Safety",
    "fire/safety": "Fire & Safety",
    "fire alarm": "Fire & Safety",
    "sprinkler": "Fire & Safety",
    "emergency systems": "Fire & Safety",
    "safety equipment": "Fire & Safety",
    "first aid": "Fire & Safety",
    # Pest Control
    "pest control": "Pest Control",
    "pest": "Pest Control",
    "exterminator": "Pest Control",
    "pest sighting": "Pest Control",
    "wildlife": "Pest Control",
    # Cleaning / Janitorial
    "cleaning": "Cleaning",
    "janitorial": "Cleaning",
    "housekeeping": "Cleaning",
    "waste management": "Cleaning",
    "recycling": "Cleaning",
    "restroom supplies": "Cleaning",
    # Security / Access
    "security": "Security",
    "security systems": "Security",
    "badge/access": "Security",
    "access control": "Security",
    "surveillance": "Security",
    "alarm systems": "Security",
    "key management": "Security",
    "doors/locks": "Security",
    # Network / IT
    "network": "IT & Network",
    "it/network": "IT & Network",
    "it": "IT & Network",
    "it support": "IT & Network",
    "connectivity": "IT & Network",
    "wifi": "IT & Network",
    "telecom": "IT & Network",
    "audio/visual": "IT & Network",
    "data center": "IT & Network",
    "server room": "IT & Network",
    # General / Maintenance
    "general maintenance": "General Maintenance",
    "maintenance": "General Maintenance",
    "general": "General Maintenance",
    # Facilities / Building
    "structural": "Facilities",
    "roofing": "Facilities",
    "windows": "Facilities",
    "paint": "Facilities",
    "carpentry": "Facilities",
    "grounds/landscaping": "Facilities",
    "parking": "Facilities",
    "signage": "Facilities",
    "furniture": "Facilities",
    "appliances": "Facilities",
    "kitchen equipment": "Facilities",
    "vending": "Facilities",
    "cubicle/workspace": "Facilities",
    "conference room equipment": "Facilities",
    "ergonomics": "Facilities",
    "moving/relocation": "Facilities",
    "event setup": "Facilities",
    # Fleet / Logistics
    "fleet services": "Fleet & Logistics",
    "fuel systems": "Fleet & Logistics",
    "shipping/receiving": "Fleet & Logistics",
    "mail services": "Fleet & Logistics",
    "visitor management": "Security",
    # Health / Environmental
    "mold/mildew": "Health & Environmental",
    "asbestos": "Health & Environmental",
    "lead": "Health & Environmental",
    "radon": "Health & Environmental",
    "hazardous materials": "Health & Environmental",
    "noise complaint": "Health & Environmental",
    "odor complaint": "Health & Environmental",
    # Compliance
    "ada compliance": "Compliance",
    "inspection": "Compliance",
    "permit": "Compliance",
    "code violation": "Compliance",
    # Misc / Catch-all
    "misc": "Other",
    "other": "Other",
}

# Priority normalization
PRIORITY_MAPPING = {
    "critical": "CRITICAL", "crit": "CRITICAL",
    "high": "HIGH", "hi": "HIGH",
    "medium": "MEDIUM", "med": "MEDIUM", "normal": "MEDIUM",
    "low": "LOW", "lo": "LOW",
    "urgent!!!": "CRITICAL", "asap": "HIGH",
}

# Valid statuses
VALID_STATUSES = {
    "open", "in progress", "pending vendor", "escalated",
    "resolved", "closed",
}


def parse_date_safe(value: str):
    """Parse a date string using multiple strategies. Returns datetime or None."""
    if not value or not value.strip():
        return None
    val = value.strip()

    # TBD / garbage
    if val.upper() in ("TBD", "N/A", "NULL", "???"):
        return None

    # Unix timestamp (10 digits, seconds since epoch)
    if re.match(r"^\d{10}$", val):
        try:
            return datetime.fromtimestamp(int(val), tz=timezone.utc)
        except (ValueError, OSError):
            pass

    # Try dateutil (handles ISO, US slash, US dash, Euro dash, AM/PM)
    try:
        return parse_date(val, dayfirst=False, fuzzy=True)
    except (ParserError, ValueError, OverflowError):
        pass

    # Last resort: date-only
    try:
        return datetime.strptime(val[:10], "%Y-%m-%d")
    except ValueError:
        pass

    return None


def clean_cost(value: str):
    """Clean cost value. Returns Decimal or None."""
    if not value or not value.strip():
        return None
    val = value.strip()

    # Garbage values
    if val.upper() in ("TBD", "N/A", "ERROR", "NULL"):
        return None

    # Remove $ and commas
    clean = val.replace("$", "").replace(",", "").replace('"', "").strip()
    try:
        c = Decimal(clean)
        # Flag clearly bad sentinel values as None
        if c <= -999 or c <= 0:
            # Negative and zero costs are suspicious; null them for gold but flag in quality_flags
            return c  # Keep for silver, flag later
        if c > 100000:  # Unreasonable for facility tickets
            return None
        return c
    except (InvalidOperation, ValueError):
        return None


# ── Garbage category values to reject ─────────────────────────
GARBAGE_CATEGORIES = {"???", "asdf", "delete me", "test", "null", "", "n/a", "none", "tbd", "unknown"}

# ── Keyword-based fallback for long descriptions ──────────────
# Some rows have full sentences in the category field (data entry errors).
# These keywords let us classify them rather than producing title-cased noise.
CATEGORY_KEYWORDS = [
    ("elevator", "Elevator"),
    ("lift", "Elevator"),
    ("toilet", "Plumbing"),
    ("faucet", "Plumbing"),
    ("pipe burst", "Plumbing"),
    ("water leak", "Plumbing"),
    ("hot water", "Plumbing"),
    ("overflowing", "Plumbing"),
    ("leak", "Plumbing"),
    ("plumbing", "Plumbing"),
    ("ac unit", "HVAC"),
    ("thermo", "HVAC"),
    ("temperature", "HVAC"),
    ("hvac", "HVAC"),
    ("cooling", "HVAC"),
    ("heating", "HVAC"),
    ("unit", "HVAC"),
    ("cycling", "HVAC"),
    ("breaker", "Electrical"),
    ("outlet", "Electrical"),
    ("electrical", "Electrical"),
    ("power", "Electrical"),
    ("fire extinguisher", "Fire & Safety"),
    ("smoke detector", "Fire & Safety"),
    ("emergency exit", "Fire & Safety"),
    ("sprinkler", "Fire & Safety"),
    ("security camera", "Security"),
    ("access card", "Security"),
    ("badge", "Security"),
    ("door", "Security"),
    ("lock", "Security"),
    ("wifi", "IT & Network"),
    ("network", "IT & Network"),
    ("vpn", "IT & Network"),
    ("outage", "IT & Network"),
    ("printer", "IT & Network"),
    ("desk", "Facilities"),
    ("furniture", "Facilities"),
    ("window", "Facilities"),
    ("chair", "Facilities"),
    ("restroom", "Cleaning"),
    ("cleaning", "Cleaning"),
    ("janitor", "Cleaning"),
    ("bird", "Pest Control"),
    ("bugs", "Pest Control"),
    ("wasp", "Pest Control"),
    ("pest", "Pest Control"),
    ("rodent", "Pest Control"),
    ("mold", "Health & Environmental"),
    ("asbestos", "Health & Environmental"),
    ("inspection", "Compliance"),
    ("wheelchair", "Compliance"),
    ("ada ", "Compliance"),
]


def classify_category_fallback(raw: str) -> str:
    """
    Fallback classifier for categories not in the explicit CATEGORY_MAPPING.
    Uses keyword matching for long descriptions and garbage detection.
    Returns the normalized category or None if unclassifiable.
    """
    val = raw.strip().lower()
    if not val or val in GARBAGE_CATEGORIES:
        return None
    # Check keywords
    for keyword, norm in CATEGORY_KEYWORDS:
        if keyword in val:
            return norm
    return None


def clean_sla(value: str):
    """Clean SLA hours. Returns int or None."""
    if not value or not value.strip():
        return None
    val = value.strip().upper()

    if val in ("N/A", "TBD", "NULL"):
        return None

    try:
        s = int(float(val))
        if s == 999:  # Sentinel value
            return None
        if s < 0:  # Invalid
            return None
        return s
    except (ValueError, TypeError):
        return None


def build_silver():
    """
    Transform bronze → silver.

    - Parses dates from multiple formats
    - Normalizes categories and priorities
    - Cleans cost and SLA fields
    - Flags duplicates (by resolution_notes pattern)
    - Validates data (resolved_at >= created_at)
    - Records data quality issues in JSONB flags

    Returns:
        int: Number of rows loaded to silver.
    """
    logger.info("=== SILVER LAYER: Starting transformation ===")
    truncate_table(SILVER_SCHEMA, SILVER_TABLE)

    # Fetch all bronze rows
    with get_cursor() as cur:
        cur.execute(f"SELECT * FROM {BRONZE_SCHEMA}.{BRONZE_TABLE}")
        columns = [desc[0] for desc in cur.description]
        bronze_rows = [dict(zip(columns, row)) for row in cur.fetchall()]

    logger.info(f"Fetched {len(bronze_rows)} rows from bronze")

    insert_sql = f"""
        INSERT INTO {SILVER_SCHEMA}.{SILVER_TABLE}
            (ticket_id, created_at, resolved_at, category_raw, category_normalized,
             priority, status, building, description, submitted_by, assigned_to,
             resolution_notes, cost, sla_hours, is_duplicate, data_quality_flags,
             silver_processed_at)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """

    stats = {
        "total": 0,
        "loaded": 0,
        "skipped_duplicate": 0,
        "skipped_null_ticket_id": 0,
        "date_parse_failures": 0,
        "cost_cleaned": 0,
        "sla_cleaned": 0,
        "priority_normalized": 0,
        "category_normalized": 0,
    }

    with get_cursor() as cur:
        for row in bronze_rows:
            stats["total"] += 1
            flags = {}

            # Skip rows with no ticket_id
            tid = (row.get("ticket_id") or "").strip()
            if not tid or tid.upper() in ("N/A", "NULL"):
                stats["skipped_null_ticket_id"] += 1
                continue

            # Skip duplicate tickets (flagged in resolution_notes)
            res_notes = (row.get("resolution_notes") or "")
            is_dup = "duplicate of ticket" in res_notes.lower()
            if is_dup:
                stats["skipped_duplicate"] += 1
                # Still load but flag; don't skip — interviewer may want to see
                # Actually, let's skip true duplicates to keep silver clean
                continue

            # Parse dates
            created_at = parse_date_safe(row.get("created_at", ""))
            resolved_at = parse_date_safe(row.get("resolved_at", ""))
            if not created_at:
                stats["date_parse_failures"] += 1
                flags["created_at_unparseable"] = row.get("created_at", "")
            if not resolved_at and row.get("resolved_at", "").strip():
                stats["date_parse_failures"] += 1
                flags["resolved_at_unparseable"] = row.get("resolved_at", "")

            # Validate: resolved_at >= created_at
            if created_at and resolved_at and resolved_at < created_at:
                flags["resolved_before_created"] = True

            # Normalize category
            raw_cat = (row.get("category") or "").strip().lower()
            norm_cat = CATEGORY_MAPPING.get(raw_cat)
            if not norm_cat:
                # Try keyword-based fallback for long descriptions
                norm_cat = classify_category_fallback(raw_cat)
            if not norm_cat and raw_cat:
                # Check garbage (already rejected by fallback but just in case)
                if raw_cat in GARBAGE_CATEGORIES:
                    norm_cat = None
                    flags["garbage_category"] = raw_cat
                else:
                    # Truly unclassifiable — flag and use title-case as last resort
                    norm_cat = raw_cat.title()
                    flags["unclassified_category"] = raw_cat
            if norm_cat and norm_cat != raw_cat:
                stats["category_normalized"] += 1

            # Normalize priority
            raw_pri = (row.get("priority") or "").strip().lower()
            norm_pri = PRIORITY_MAPPING.get(raw_pri, raw_pri.upper() if raw_pri else None)
            if norm_pri and norm_pri != raw_pri.upper():
                stats["priority_normalized"] += 1
            if norm_pri and norm_pri not in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
                flags["unrecognized_priority"] = raw_pri
                norm_pri = "MEDIUM"  # Default fallback

            # Validate status
            raw_status = (row.get("status") or "").strip().lower()
            if raw_status not in VALID_STATUSES and raw_status:
                flags["unrecognized_status"] = raw_status

            # Clean cost
            cost = clean_cost(row.get("cost", ""))
            if cost is not None and cost < 0:
                flags["negative_cost"] = str(cost)
                cost = None
            if cost is not None and cost == 0:
                flags["zero_cost"] = True
            if cost is not None:
                stats["cost_cleaned"] += 1

            # Clean SLA
            sla = clean_sla(row.get("sla_hours", ""))
            if sla is not None:
                stats["sla_cleaned"] += 1

            cur.execute(insert_sql, (
                tid,
                created_at,
                resolved_at,
                raw_cat,
                norm_cat,
                norm_pri,
                raw_status.title() if raw_status else None,
                (row.get("building") or "").strip() or None,
                (row.get("description") or "").strip() or None,
                (row.get("submitted_by") or "").strip() or None,
                (row.get("assigned_to") or "").strip() or None,
                res_notes.strip() or None,
                cost,
                sla,
                False,  # is_duplicate
                json.dumps(flags) if flags else None,
                datetime.now(timezone.utc),
            ))
            stats["loaded"] += 1

    logger.info(f"Silver transformation complete.")
    logger.info(f"  Total bronze rows:     {stats['total']}")
    logger.info(f"  Loaded to silver:      {stats['loaded']}")
    logger.info(f"  Skipped (null id):     {stats['skipped_null_ticket_id']}")
    logger.info(f"  Skipped (duplicates):  {stats['skipped_duplicate']}")
    logger.info(f"  Date parse failures:   {stats['date_parse_failures']}")
    logger.info(f"  Categories normalized: {stats['category_normalized']}")
    logger.info(f"  Priorities normalized: {stats['priority_normalized']}")
    return stats["loaded"]
