"""
Semantic Classification Agent (Agent C)

Takes the 98 raw, inconsistent category values from the bronze layer and
proposes a normalized mapping to ~8-10 clean business categories.

This agent shines where rule-based approaches fail: understanding that
"elevator/escalator", "lift", and "vertical transport" all mean the same
thing requires semantic understanding, not just string matching.

Modes:
  1. DETERMINISTIC: uses a pre-built mapping (curated with LLM assistance)
  2. LLM_ASSIST: calls an LLM API to generate/refine the mapping
  3. PROMPT_ONLY: outputs the prompt for review/human-in-the-loop
"""

import json
import logging
from datetime import datetime, timezone

from src.config import RAW_CATEGORIES, AGENT_OUTPUT_DIR

logger = logging.getLogger(__name__)

# ── Normalized category definitions ─────────────────────────────────
# These are the target categories. The agent maps each raw category to one of these.
TARGET_CATEGORIES = {
    "Elevator": "Elevators, escalators, lifts, vertical transport equipment",
    "Electrical": "Power issues, lighting, generators, UPS, electrical systems",
    "HVAC": "Heating, cooling, air conditioning, climate control, temperature, humidity",
    "Plumbing": "Water issues, leaks, flooding, plumbing, restroom fixtures",
    "Fire & Safety": "Fire alarms, sprinklers, emergency systems, safety equipment, first aid",
    "Pest Control": "Pest sightings, extermination, wildlife removal",
    "Cleaning": "Janitorial, housekeeping, waste management, recycling, restroom supplies",
    "Security": "Access control, badge systems, surveillance, locks, alarms, key management",
    "IT & Network": "Network connectivity, WiFi, IT support, telecom, servers, AV equipment",
    "General Maintenance": "General repairs, maintenance requests not fitting other categories",
    "Facilities": "Structural, roofing, painting, carpentry, grounds, parking, furniture",
    "Health & Environmental": "Mold, asbestos, air quality complaints, hazardous materials",
    "Compliance": "ADA compliance, inspections, permits, code violations",
    "Fleet & Logistics": "Fleet services, fuel, shipping, mail services",
    "Other": "Miscellaneous, uncategorized, or ambiguous requests",
}


def build_deterministic_mapping():
    """
    Build the category mapping using a pre-curated dictionary.

    This mapping was originally generated by an LLM (prompt below in build_llm_prompt),
    reviewed by a human, and committed as code. The agent's job is to maintain and
    explain this mapping — not to regenerate it from scratch every run.
    """
    # This is the same mapping used by silver.py's CATEGORY_MAPPING.
    # It lives here as the agent's "source of truth" and in silver.py as the runtime.
    mapping = {
        # Elevator
        "elevator": "Elevator",
        "elevator/escalator": "Elevator",
        "lift": "Elevator",
        "vertical transport": "Elevator",
        # Electrical
        "electrical": "Electrical",
        "electrical systems": "Electrical",
        "elec": "Electrical",
        "power": "Electrical",
        "power issue": "Electrical",
        "lighting": "Electrical",
        "generator": "Electrical",
        "ups/battery": "Electrical",
        # HVAC
        "hvac": "HVAC",
        "a/c": "HVAC",
        "climate control": "HVAC",
        "heating/cooling": "HVAC",
        "temperature control": "HVAC",
        "humidity": "HVAC",
        "indoor air quality": "HVAC",
        # Plumbing
        "plumbing": "Plumbing",
        "plumbing issue": "Plumbing",
        "water/plumbing": "Plumbing",
        "water issue": "Plumbing",
        "flooding": "Plumbing",
        "leak": "Plumbing",
        # Fire & Safety
        "fire safety": "Fire & Safety",
        "fire/safety": "Fire & Safety",
        "fire alarm": "Fire & Safety",
        "sprinkler": "Fire & Safety",
        "emergency systems": "Fire & Safety",
        "safety equipment": "Fire & Safety",
        "first aid": "Fire & Safety",
        # Pest Control
        "pest control": "Pest Control",
        "pest": "Pest Control",
        "exterminator": "Pest Control",
        "pest sighting": "Pest Control",
        "wildlife": "Pest Control",
        # Cleaning
        "cleaning": "Cleaning",
        "janitorial": "Cleaning",
        "housekeeping": "Cleaning",
        "waste management": "Cleaning",
        "recycling": "Cleaning",
        "restroom supplies": "Cleaning",
        # Security
        "security": "Security",
        "security systems": "Security",
        "badge/access": "Security",
        "access control": "Security",
        "surveillance": "Security",
        "alarm systems": "Security",
        "key management": "Security",
        "doors/locks": "Security",
        "visitor management": "Security",
        # IT & Network
        "network": "IT & Network",
        "it/network": "IT & Network",
        "it": "IT & Network",
        "it support": "IT & Network",
        "connectivity": "IT & Network",
        "wifi": "IT & Network",
        "telecom": "IT & Network",
        "audio/visual": "IT & Network",
        "data center": "IT & Network",
        "server room": "IT & Network",
        "conference room equipment": "IT & Network",
        # General Maintenance
        "general maintenance": "General Maintenance",
        "maintenance": "General Maintenance",
        "general": "General Maintenance",
        # Facilities
        "structural": "Facilities",
        "roofing": "Facilities",
        "windows": "Facilities",
        "paint": "Facilities",
        "carpentry": "Facilities",
        "grounds/landscaping": "Facilities",
        "parking": "Facilities",
        "signage": "Facilities",
        "furniture": "Facilities",
        "appliances": "Facilities",
        "kitchen equipment": "Facilities",
        "vending": "Facilities",
        "cubicle/workspace": "Facilities",
        "ergonomics": "Facilities",
        "moving/relocation": "Facilities",
        "event setup": "Facilities",
        # Fleet & Logistics
        "fleet services": "Fleet & Logistics",
        "fuel systems": "Fleet & Logistics",
        "shipping/receiving": "Fleet & Logistics",
        "mail services": "Fleet & Logistics",
        # Health & Environmental
        "mold/mildew": "Health & Environmental",
        "asbestos": "Health & Environmental",
        "lead": "Health & Environmental",
        "radon": "Health & Environmental",
        "hazardous materials": "Health & Environmental",
        "noise complaint": "Health & Environmental",
        "odor complaint": "Health & Environmental",
        # Compliance
        "ada compliance": "Compliance",
        "inspection": "Compliance",
        "permit": "Compliance",
        "code violation": "Compliance",
        # Other
        "misc": "Other",
        "other": "Other",
    }

    return mapping


def run_semantic_classification_agent(mode="deterministic"):
    """
    Run the Semantic Classification Agent.

    Args:
        mode: "deterministic" (default), "prompt_only", or "llm_assist"

    Returns:
        dict with mapping, coverage stats, and confidence assessment.
    """
    logger.info("=== AGENT: Semantic Classification Agent ===")
    logger.info(f"Input: {len(RAW_CATEGORIES)} unique raw category values")

    if mode == "prompt_only":
        prompt = build_llm_prompt()
        output_path = AGENT_OUTPUT_DIR / "semantic_classification_prompt.txt"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(prompt)
        logger.info(f"LLM prompt written to {output_path}")
        return {"mode": "prompt_only", "prompt_file": str(output_path)}

    mapping = build_deterministic_mapping()

    # Calculate coverage
    raw_set = set(c.lower() for c in RAW_CATEGORIES)
    mapped_set = set(mapping.keys())
    coverage_pct = round(len(mapped_set) / len(raw_set) * 100, 2) if raw_set else 0
    unmapped = raw_set - mapped_set

    # Group by target
    target_counts = {}
    for raw, normalized in mapping.items():
        target_counts[normalized] = target_counts.get(normalized, 0) + 1

    result = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "mode": "deterministic",
        "input_categories": len(raw_set),
        "mapped_categories": len(mapped_set),
        "coverage_pct": coverage_pct,
        "target_categories": len(target_counts),
        "target_distribution": target_counts,
        "unmapped": sorted(unmapped),
        "mapping": mapping,
    }

    output_path = AGENT_OUTPUT_DIR / "semantic_classification_result.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(result, indent=2))

    logger.info(f"Coverage: {coverage_pct}% ({len(mapped_set)}/{len(raw_set)} mapped)")
    logger.info(f"Target categories: {len(target_counts)}")
    for target, count in sorted(target_counts.items(), key=lambda x: -x[1]):
        logger.info(f"  {target}: {count} raw values")
    if unmapped:
        logger.warning(f"  Unmapped: {unmapped}")
    logger.info(f"Full result → {output_path}")

    return result


def build_llm_prompt():
    """Build the prompt that generated the mapping above."""
    categories_formatted = "\n".join(f"  - {c}" for c in sorted(RAW_CATEGORIES))
    targets_formatted = "\n".join(
        f"  - {k}: {v}" for k, v in TARGET_CATEGORIES.items()
    )

    return f"""You are a Semantic Classification Agent for a facility maintenance system.
Your task: normalize {len(RAW_CATEGORIES)} messy, inconsistent category values
into a clean set of standard business categories.

## Raw Categories (messy, from actual data)
{categories_formatted}

## Target Categories (the business wants these)
{targets_formatted}

## Rules
1. Map EVERY raw category to exactly ONE target category.
2. Be case-insensitive and handle synonyms:
   - "elevator", "lift", "vertical transport" → Elevator
   - "hvac", "a/c", "climate control" → HVAC
   - "janitorial", "housekeeping" → Cleaning
3. If a raw category is ambiguous, pick the most likely target and mark confidence < 1.0.
4. If truly unmappable, map to "Other".

## Output Format
Return a JSON object where:
- keys are the EXACT lowercase raw category strings
- values are objects with: "target" (string), "confidence" (0.0-1.0), "reasoning" (string)

Example:
{{
  "elevator": {{"target": "Elevator", "confidence": 1.0, "reasoning": "Direct match"}},
  "vertical transport": {{"target": "Elevator", "confidence": 1.0, "reasoning": "Synonym for elevator equipment"}},
  "power issue": {{"target": "Electrical", "confidence": 0.95, "reasoning": "Power is a subset of Electrical"}}
}}

## Important
- Output ONLY valid JSON, no markdown wrapping, no explanation text.
- Map ALL {len(RAW_CATEGORIES)} categories — do not skip any.
- For food-service items (vending, kitchen equipment), map to Facilities.
"""
